### ISSUE TITLE
Dataset Preprocessing

### ISSUE THREAD

**Issue by ubaidfayyaz** [ItsKarma1/SPY-I-Smart-Predictive-Policing#1]
Dataset preprocessing task, @ItsKarma1 add more detail to it and assign it to a few people. Clearly, state what are the outcome of this task like would it be some document, some piece of code, etc.

**Comment by Mubeen-Khan14** [comment]
**Data-set Pre-processing for suspicious activity detection (Assigned to Mubeen and Mishaal)**
The data-set used in the anomaly detection is very big in size i.e about 34 GB of memory. So initially what we are doing is extracting particular frames (16 in total) from all the videos in the data-set and then in order to further reduce the size merging all the extracted frames into one such that the entire pattern of the activity is detected.

**Crowd Density Estimation (Assigned to Fatima and Zarafshan)**

**Comment by ubaidfayyaz** [comment]
@ItsKarma1 Please create separate issue and assign to a participant on github. 

https://help.github.jp/enterprise/2.11/user/articles/assigning-issues-and-pull-requests-to-other-github-users/

**Comment by Mubeen-Khan14** [comment]
Separate issues have been created and details along with the assigned members on that task will be described in a bit too.

**Comment by Mubeen-Khan14** [comment]
All weekly or necessary updates will also be provided in that respective issue.
