### ISSUE TITLE
Crowd Counting

### ISSUE THREAD

**Issue by Mubeen-Khan14** [ItsKarma1/SPY-I-Smart-Predictive-Policing#6]

**Comment by Fatima1017** [comment]
We have initiated the task of crowd counting by training a model on 30 images to test the results. As the training set is very small, the results obtained are not accurate enough. So, in order to achieve good accuracy, we will be increasing the size of the dataset and will perform further modifications such as modification in anchor box sizes to achieve the desired results.
The results are shown below
![result0023](https://user-images.githubusercontent.com/65360197/98432368-3e4d9600-20df-11eb-93df-ca7e51ce9d93.jpg)
